// GENERATED — DO NOT EDIT.
// Source: docs/reference/models.yaml
// Regenerate with: dart run tool/gen_models.dart
// ignore_for_file: lines_longer_than_80_chars

import 'package:glue/src/catalog/model_catalog.dart';

const ModelCatalog bundledCatalog = ModelCatalog(
  version: 1,
  updatedAt: '2026-04-19',
  defaults: DefaultsConfig(
    model: 'anthropic/claude-sonnet-4.6',
    smallModel: 'openai/gpt-5.4-mini',
    localModel: 'ollama/qwen2.5-coder:32b',
  ),
  capabilities: {
    'binary_tool_results': 'Accepts binary or multimodal tool-result payloads.',
    'browser': 'Suitable for browser/research workflows.',
    'chat': 'Text chat.',
    'coding': 'Strong code generation and code review behavior.',
    'files': 'File upload or file reference support.',
    'json': 'Structured JSON output.',
    'local': 'Runs locally or on a user-controlled endpoint.',
    'parallel_tools': 'Parallel tool-call execution in a single turn.',
    'reasoning': 'Explicit reasoning effort or thinking controls.',
    'streaming': 'Incremental token streaming.',
    'tools': 'Tool calling or function calling.',
    'vision': 'Image input.',
  },
  providers: {
    'anthropic': ProviderDef(
      id: 'anthropic',
      name: 'Anthropic',
      adapter: 'anthropic',
      compatibility: null,
      enabled: true,
      baseUrl: null,
      docsUrl: 'https://docs.anthropic.com/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'ANTHROPIC_API_KEY'),
      requestHeaders: {},
      models: {
        'claude-sonnet-4.6': ModelDef(
          id: 'claude-sonnet-4.6',
          name: 'Claude Sonnet 4.6',
          recommended: true,
          isDefault: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Default high-quality coding model.',
        ),
        'claude-opus-4.6': ModelDef(
          id: 'claude-opus-4.6',
          name: 'Claude Opus 4.6',
          recommended: true,
          isDefault: false,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'slower',
          cost: 'premium',
          notes:
              'Use for difficult architecture, debugging, and long investigations.',
        ),
        'claude-haiku-4.5': ModelDef(
          id: 'claude-haiku-4.5',
          name: 'Claude Haiku 4.5',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Good small_model candidate for titles, summaries, and quick checks.',
        ),
      },
    ),
    'openai': ProviderDef(
      id: 'openai',
      name: 'OpenAI',
      adapter: 'openai',
      compatibility: null,
      enabled: true,
      baseUrl: 'https://api.openai.com/v1',
      docsUrl: 'https://platform.openai.com/docs/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'OPENAI_API_KEY'),
      requestHeaders: {},
      models: {
        'gpt-5.4': ModelDef(
          id: 'gpt-5.4',
          name: 'GPT-5.4',
          recommended: true,
          isDefault: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Frontier general-purpose and agentic coding model.',
        ),
        'gpt-5.4-mini': ModelDef(
          id: 'gpt-5.4-mini',
          name: 'GPT-5.4 Mini',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Default small_model candidate.',
        ),
        'gpt-5.3-codex': ModelDef(
          id: 'gpt-5.3-codex',
          name: 'GPT-5.3 Codex',
          recommended: true,
          isDefault: false,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Coding-specialized model.',
        ),
        'gpt-5.2': ModelDef(
          id: 'gpt-5.2',
          name: 'GPT-5.2',
          recommended: false,
          isDefault: false,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Keep visible only if users still rely on it.',
        ),
      },
    ),
    'gemini': ProviderDef(
      id: 'gemini',
      name: 'Google Gemini',
      adapter: 'gemini',
      compatibility: null,
      enabled: true,
      baseUrl: null,
      docsUrl: 'https://ai.google.dev/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'GEMINI_API_KEY'),
      requestHeaders: {},
      models: {
        'gemini-pro-latest': ModelDef(
          id: 'gemini-pro-latest',
          name: 'Gemini Pro Latest',
          recommended: true,
          isDefault: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes: 'Stable alias for the current Pro-class Gemini model.',
        ),
        'gemini-flash-latest': ModelDef(
          id: 'gemini-flash-latest',
          name: 'Gemini Flash Latest',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'files', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Fast model for summarization, extraction, and browser-heavy work.',
        ),
      },
    ),
    'mistral': ProviderDef(
      id: 'mistral',
      name: 'Mistral AI',
      adapter: 'openai',
      compatibility: 'mistral',
      enabled: true,
      baseUrl: 'https://api.mistral.ai/v1',
      docsUrl: 'https://docs.mistral.ai/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'MISTRAL_API_KEY'),
      requestHeaders: {},
      models: {
        'mistral-large-latest': ModelDef(
          id: 'mistral-large-latest',
          name: 'Mistral Large Latest',
          recommended: true,
          isDefault: true,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes: 'General Mistral default.',
        ),
        'mistral-small-latest': ModelDef(
          id: 'mistral-small-latest',
          name: 'Mistral Small Latest',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'json', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Good for quick tasks and summaries.',
        ),
        'codestral-latest': ModelDef(
          id: 'codestral-latest',
          name: 'Codestral Latest',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 256000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes: 'Coding-focused Mistral model.',
        ),
      },
    ),
    'groq': ProviderDef(
      id: 'groq',
      name: 'Groq',
      adapter: 'openai',
      compatibility: 'groq',
      enabled: true,
      baseUrl: 'https://api.groq.com/openai/v1',
      docsUrl: 'https://console.groq.com/docs/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'GROQ_API_KEY'),
      requestHeaders: {},
      models: {
        'qwen/qwen3-coder': ModelDef(
          id: 'qwen/qwen3-coder',
          name: 'Qwen3 Coder',
          recommended: true,
          isDefault: true,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 262000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Fast coding model through an OpenAI-compatible endpoint.',
        ),
        'llama-3.3-70b-versatile': ModelDef(
          id: 'llama-3.3-70b-versatile',
          name: 'Llama 3.3 70B Versatile',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'json', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'General fast hosted open model.',
        ),
      },
    ),
    'ollama': ProviderDef(
      id: 'ollama',
      name: 'Ollama',
      adapter: 'openai',
      compatibility: 'ollama',
      enabled: true,
      baseUrl: 'http://localhost:11434/v1',
      docsUrl: 'https://ollama.com/',
      auth: AuthSpec(kind: AuthKind.none, envVar: null),
      requestHeaders: {},
      models: {
        'qwen2.5-coder:32b': ModelDef(
          id: 'qwen2.5-coder:32b',
          name: 'Qwen2.5 Coder 32B',
          recommended: true,
          isDefault: true,
          capabilities: {'chat', 'coding', 'json', 'local'},
          contextWindow: 32768,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'Sensible local coding default if the machine can run it.',
        ),
        'devstral:latest': ModelDef(
          id: 'devstral:latest',
          name: 'Devstral Latest',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'Local agentic coding candidate.',
        ),
        'llama3.2:latest': ModelDef(
          id: 'llama3.2:latest',
          name: 'Llama 3.2 Latest',
          recommended: false,
          isDefault: false,
          capabilities: {'chat', 'json', 'local'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'General local fallback.',
        ),
      },
    ),
    'openrouter': ProviderDef(
      id: 'openrouter',
      name: 'OpenRouter',
      adapter: 'openai',
      compatibility: 'openrouter',
      enabled: false,
      baseUrl: 'https://openrouter.ai/api/v1',
      docsUrl: 'https://openrouter.ai/docs/',
      auth: AuthSpec(kind: AuthKind.env, envVar: 'OPENROUTER_API_KEY'),
      requestHeaders: {
        'HTTP-Referer': 'https://getglue.dev',
        'X-Title': 'Glue',
      },
      models: {
        'anthropic/claude-sonnet-4.6': ModelDef(
          id: 'anthropic/claude-sonnet-4.6',
          name: 'Claude Sonnet 4.6 via OpenRouter',
          recommended: true,
          isDefault: false,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'provider_routed',
          notes: 'Useful when users want one router key.',
        ),
        'openai/gpt-5.4-mini': ModelDef(
          id: 'openai/gpt-5.4-mini',
          name: 'GPT-5.4 Mini via OpenRouter',
          recommended: true,
          isDefault: false,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'provider_routed',
          notes: 'Small-model fallback through a router.',
        ),
        'google/gemini-flash-latest': ModelDef(
          id: 'google/gemini-flash-latest',
          name: 'Gemini Flash Latest via OpenRouter',
          recommended: true,
          isDefault: false,
          capabilities: {'browser', 'chat', 'files', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'provider_routed',
          notes: 'Good for research and extraction workflows.',
        ),
      },
    ),
    'local-vllm': ProviderDef(
      id: 'local-vllm',
      name: 'Local vLLM',
      adapter: 'openai',
      compatibility: 'vllm',
      enabled: false,
      baseUrl: 'http://localhost:8000/v1',
      docsUrl: null,
      auth: AuthSpec(kind: AuthKind.none, envVar: null),
      requestHeaders: {},
      models: {
        'local-model': ModelDef(
          id: 'local-model',
          name: 'Local Model',
          recommended: false,
          isDefault: false,
          capabilities: {'chat', 'json', 'local'},
          contextWindow: null,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Rename this entry to the model served by vLLM, LM Studio, or another local gateway.',
        ),
      },
    ),
  },
);
