// GENERATED — DO NOT EDIT.
// Source: docs/reference/models.yaml
// Regenerate with: dart run tool/gen_models.dart
// ignore_for_file: lines_longer_than_80_chars

import 'package:glue/src/catalog/model_catalog.dart';

const ModelCatalog bundledCatalog = ModelCatalog(
  version: 1,
  updatedAt: '2026-04-25',
  defaults: DefaultsConfig(
    model: 'anthropic/claude-sonnet-4-7',
    smallModel: 'openai/gpt-5.4-mini',
    localModel: 'ollama/gemma4:26b',
  ),
  capabilities: {
    'binary_tool_results': 'Accepts binary or multimodal tool-result payloads.',
    'browser': 'Suitable for browser/research workflows.',
    'chat': 'Text chat.',
    'coding': 'Strong code generation and code review behavior.',
    'files': 'File upload or file reference support.',
    'json': 'Structured JSON output.',
    'local': 'Runs locally or on a user-controlled endpoint.',
    'parallel_tools': 'Parallel tool-call execution in a single turn.',
    'reasoning': 'Explicit reasoning effort or thinking controls.',
    'streaming': 'Incremental token streaming.',
    'tools': 'Tool calling or function calling.',
    'vision': 'Image input.',
  },
  providers: {
    'anthropic': ProviderDef(
      id: 'anthropic',
      name: 'Anthropic',
      adapter: 'anthropic',
      compatibility: null,
      enabled: true,
      baseUrl: null,
      docsUrl: 'https://docs.anthropic.com/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'ANTHROPIC_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {},
      models: {
        'claude-sonnet-4-6': ModelDef(
          id: 'claude-sonnet-4-6',
          name: 'Claude Sonnet 4.6',
          apiId: 'claude-sonnet-4-6',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: 64000,
          speed: 'standard',
          cost: 'high',
          notes: 'Default high-quality coding model.',
        ),
        'claude-opus-4-6': ModelDef(
          id: 'claude-opus-4-6',
          name: 'Claude Opus 4.6',
          apiId: 'claude-opus-4-6',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: 128000,
          speed: 'slower',
          cost: 'premium',
          notes:
              'Use for difficult architecture, debugging, and long investigations.',
        ),
        'claude-haiku-4-5': ModelDef(
          id: 'claude-haiku-4-5',
          name: 'Claude Haiku 4.5',
          apiId: 'claude-haiku-4-5',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 200000,
          maxOutputTokens: 64000,
          speed: 'fast',
          cost: 'low',
          notes:
              'Good small_model candidate for titles, summaries, and quick checks.',
        ),
        'claude-opus-4-7': ModelDef(
          id: 'claude-opus-4-7',
          name: 'Claude Opus 4.7',
          apiId: 'claude-opus-4-7',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: 128000,
          speed: 'slower',
          cost: 'premium',
          notes:
              'Most capable Claude model — agentic coding and long-horizon work.',
        ),
      },
    ),
    'openai': ProviderDef(
      id: 'openai',
      name: 'OpenAI',
      adapter: 'openai',
      compatibility: null,
      enabled: true,
      baseUrl: 'https://api.openai.com/v1',
      docsUrl: 'https://platform.openai.com/docs/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'OPENAI_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {},
      models: {
        'gpt-5.5': ModelDef(
          id: 'gpt-5.5',
          name: 'GPT-5.5',
          apiId: 'gpt-5.5',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Frontier general-purpose and agentic coding model.',
        ),
        'gpt-5.4': ModelDef(
          id: 'gpt-5.4',
          name: 'GPT-5.4',
          apiId: 'gpt-5.4',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes: 'Prior frontier model — kept for pinned configs.',
        ),
        'gpt-5.4-mini': ModelDef(
          id: 'gpt-5.4-mini',
          name: 'GPT-5.4 Mini',
          apiId: 'gpt-5.4-mini',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Default small_model candidate.',
        ),
        'o3': ModelDef(
          id: 'o3',
          name: 'o3',
          apiId: 'o3',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'reasoning', 'tools'},
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'slower',
          cost: 'high',
          notes:
              'Reasoning-specialized flagship. State of the art on Codeforces / SWE-bench / MMMU; use for hard debugging, proofs, and multi-step planning.',
        ),
        'o4-mini': ModelDef(
          id: 'o4-mini',
          name: 'o4-mini',
          apiId: 'o4-mini',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'reasoning', 'tools'},
          contextWindow: 200000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Small + fast reasoning model. Best price/quality point for iterative coding with structured thinking.',
        ),
        'gpt-5.2': ModelDef(
          id: 'gpt-5.2',
          name: 'GPT-5.2',
          apiId: 'gpt-5.2',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'high',
          notes:
              'Legacy frontier model — superseded by GPT-5.4. Kept for users with pinned configs.',
        ),
      },
    ),
    'gemini': ProviderDef(
      id: 'gemini',
      name: 'Google Gemini',
      adapter: 'gemini',
      compatibility: null,
      enabled: true,
      baseUrl: null,
      docsUrl: 'https://ai.google.dev/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'GEMINI_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {},
      models: {
        'gemini-3.1-pro-preview': ModelDef(
          id: 'gemini-3.1-pro-preview',
          name: 'Gemini 3.1 Pro Preview',
          apiId: 'gemini-3.1-pro-preview',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes:
              'Current Pro-class preview. Strongest Gemini model for complex reasoning, coding, and research.',
        ),
        'gemini-3-flash-preview': ModelDef(
          id: 'gemini-3-flash-preview',
          name: 'Gemini 3 Flash Preview',
          apiId: 'gemini-3-flash-preview',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'files', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Fast, balanced, multimodal. ~78% SWE-bench Verified — strong agentic-coding candidate.',
        ),
        'gemini-3.1-flash-lite-preview': ModelDef(
          id: 'gemini-3.1-flash-lite-preview',
          name: 'Gemini 3.1 Flash-Lite Preview',
          apiId: 'gemini-3.1-flash-lite-preview',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Cost-efficient, fastest performance for high-frequency, lightweight tasks.',
        ),
        'gemini-2.5-pro': ModelDef(
          id: 'gemini-2.5-pro',
          name: 'Gemini 2.5 Pro',
          apiId: 'gemini-2.5-pro',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes:
              'GA Pro model. Retires 2026-06-17 — prefer 3.1 Pro Preview for new work.',
        ),
        'gemini-2.5-flash': ModelDef(
          id: 'gemini-2.5-flash',
          name: 'Gemini 2.5 Flash',
          apiId: 'gemini-2.5-flash',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'files', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'GA Flash. Retires 2026-06-17 — prefer 3 Flash Preview for new work.',
        ),
        'gemini-2.5-flash-lite': ModelDef(
          id: 'gemini-2.5-flash-lite',
          name: 'Gemini 2.5 Flash-Lite',
          apiId: 'gemini-2.5-flash-lite',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'GA Flash-Lite. Retires 2026-06-17.',
        ),
        'deep-research-pro-preview-12-2025': ModelDef(
          id: 'deep-research-pro-preview-12-2025',
          name: 'Deep Research Pro (Dec 2025)',
          apiId: 'deep-research-pro-preview-12-2025',
          recommended: false,
          isDefault: false,
          enabled: false,
          capabilities: {'chat', 'reasoning', 'tools'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'slower',
          cost: 'high',
          notes:
              'Deep Research agent (legacy preview). Requires background-execution runner — not yet wired up in Glue.',
        ),
        'deep-research-preview-04-2026': ModelDef(
          id: 'deep-research-preview-04-2026',
          name: 'Deep Research Preview (Apr 2026)',
          apiId: 'deep-research-preview-04-2026',
          recommended: false,
          isDefault: false,
          enabled: false,
          capabilities: {'browser', 'chat', 'reasoning', 'tools'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'slower',
          cost: 'high',
          notes:
              'Fast Deep Research agent — interactive use. Requires background runner (not yet wired up in Glue).',
        ),
        'deep-research-max-preview-04-2026': ModelDef(
          id: 'deep-research-max-preview-04-2026',
          name: 'Deep Research Max Preview (Apr 2026)',
          apiId: 'deep-research-max-preview-04-2026',
          recommended: false,
          isDefault: false,
          enabled: false,
          capabilities: {'browser', 'chat', 'reasoning', 'tools'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'slower',
          cost: 'high',
          notes:
              'Maximum-comprehensiveness Deep Research agent. Requires background runner (not yet wired up in Glue).',
        ),
      },
    ),
    'mistral': ProviderDef(
      id: 'mistral',
      name: 'Mistral AI',
      adapter: 'openai',
      compatibility: 'mistral',
      enabled: true,
      baseUrl: 'https://api.mistral.ai/v1',
      docsUrl: 'https://docs.mistral.ai/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'MISTRAL_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {},
      models: {
        'devstral-latest': ModelDef(
          id: 'devstral-latest',
          name: 'Devstral Latest',
          apiId: 'devstral-latest',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 262000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes: 'Mistral\'s agentic coding model. Strong tool use.',
        ),
        'mistral-large-latest': ModelDef(
          id: 'mistral-large-latest',
          name: 'Mistral Large Latest',
          apiId: 'mistral-large-latest',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 262000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes: 'Flagship multimodal general-purpose model.',
        ),
        'mistral-small-latest': ModelDef(
          id: 'mistral-small-latest',
          name: 'Mistral Small Latest',
          apiId: 'mistral-small-latest',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 262000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Unified reasoning + coding + vision (Small 4, March 2026). Strong small-model default; cheaper than Medium with better agentic behavior.',
        ),
        'magistral-medium-latest': ModelDef(
          id: 'magistral-medium-latest',
          name: 'Magistral Medium Latest',
          apiId: 'magistral-medium-latest',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'reasoning', 'tools'},
          contextWindow: 262000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes:
              'Pure reasoning model. Use when you need explicit long-chain thinking; not a general chat pick.',
        ),
        'mistral-medium-latest': ModelDef(
          id: 'mistral-medium-latest',
          name: 'Mistral Medium Latest',
          apiId: 'mistral-medium-latest',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'tools', 'vision'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'medium',
          notes:
              'Legacy middle tier — outclassed by Small 4 on cost/quality after the March 2026 unification.',
        ),
      },
    ),
    'groq': ProviderDef(
      id: 'groq',
      name: 'Groq',
      adapter: 'openai',
      compatibility: 'groq',
      enabled: true,
      baseUrl: 'https://api.groq.com/openai/v1',
      docsUrl: 'https://console.groq.com/docs/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'GROQ_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {},
      models: {
        'llama-4-scout-17b-16e-instruct': ModelDef(
          id: 'llama-4-scout-17b-16e-instruct',
          name: 'Llama 4 Scout (17B active / 109B MoE)',
          apiId: 'meta-llama/llama-4-scout-17b-16e-instruct',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Native multimodal MoE in production on Groq. Strong speed/quality default as of 2026-04.',
        ),
        'llama-4-maverick-17b-128e-instruct': ModelDef(
          id: 'llama-4-maverick-17b-128e-instruct',
          name: 'Llama 4 Maverick (17B active / 400B MoE)',
          apiId: 'meta-llama/llama-4-maverick-17b-128e-instruct',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Larger Llama 4 variant — more capable, still Groq-fast.',
        ),
        'gpt-oss-120b': ModelDef(
          id: 'gpt-oss-120b',
          name: 'GPT-OSS 120B',
          apiId: 'openai/gpt-oss-120b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'reasoning', 'tools'},
          contextWindow: 131072,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'OpenAI\'s open-weight reasoning + coding model. 120B weights at Groq speed.',
        ),
        'gpt-oss-20b': ModelDef(
          id: 'gpt-oss-20b',
          name: 'GPT-OSS 20B',
          apiId: 'openai/gpt-oss-20b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 131072,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes: 'Coding-optimized, faster/cheaper than 120B.',
        ),
        'llama-3.3-70b-versatile': ModelDef(
          id: 'llama-3.3-70b-versatile',
          name: 'Llama 3.3 70B Versatile',
          apiId: 'llama-3.3-70b-versatile',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'tools'},
          contextWindow: 131072,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              'Previous-generation general-purpose. Superseded by Llama 4 Scout for most uses.',
        ),
        'llama-3.1-8b-instant': ModelDef(
          id: 'llama-3.1-8b-instant',
          name: 'Llama 3.1 8B Instant',
          apiId: 'llama-3.1-8b-instant',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'tools'},
          contextWindow: 131072,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'low',
          notes:
              '8B floor. Fast but tool-loop fragile; use for summaries/titles, not the main agent.',
        ),
      },
    ),
    'ollama': ProviderDef(
      id: 'ollama',
      name: 'Ollama',
      adapter: 'ollama',
      compatibility: null,
      enabled: true,
      baseUrl: 'http://localhost:11434',
      docsUrl: 'https://ollama.com/',
      auth: AuthSpec(kind: AuthKind.none, envVar: null, helpUrl: null),
      requestHeaders: {},
      models: {
        'qwen3-coder:30b': ModelDef(
          id: 'qwen3-coder:30b',
          name: 'Qwen3 Coder 30B (MoE)',
          apiId: 'qwen3-coder:30b',
          recommended: true,
          isDefault: true,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools'},
          contextWindow: 256000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Consensus local coding agent. 30B/3.3B MoE. ~20 GB VRAM at Q4_K_M.',
        ),
        'qwen3-coder-next:80b': ModelDef(
          id: 'qwen3-coder-next:80b',
          name: 'Qwen3 Coder Next 80B (MoE)',
          apiId: 'qwen3-coder-next:80b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools'},
          contextWindow: 256000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              '2026-04 flagship local coder. 3B/80B MoE; ~48 GB at Q4_K_M so needs a workstation GPU or Mac Studio. ~58% SWE-bench Verified.',
        ),
        'llama4:8b': ModelDef(
          id: 'llama4:8b',
          name: 'Llama 4 8B',
          apiId: 'llama4:8b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'local', 'tools', 'vision'},
          contextWindow: 1048576,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Massive (1M+) context with native multimodal and parallel tool calls. ~6 GB at Q4_K_M; fits laptops. Good general assistant, not a code specialist.',
        ),
        'qwen3.6:35b': ModelDef(
          id: 'qwen3.6:35b',
          name: 'Qwen3.6 35B',
          apiId: 'qwen3.6:35b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'json',
            'local',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 256000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Latest Qwen generalist with agentic coding upgrades. Vision + thinking + tools. ~24 GB at Q4_K_M.',
        ),
        'gemma4:26b': ModelDef(
          id: 'gemma4:26b',
          name: 'Gemma 4 26B',
          apiId: 'gemma4:26b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools', 'vision'},
          contextWindow: 256000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Google\'s latest with native function-calling. Multimodal, 256K context. ~18 GB at Q4_K_M.',
        ),
        'devstral-small-2:24b': ModelDef(
          id: 'devstral-small-2:24b',
          name: 'Devstral Small 2 24B',
          apiId: 'devstral-small-2:24b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Mistral\'s agentic coding model (Dec 2025). 68% SWE-bench. ~14 GB at Q4_K_M.',
        ),
        'qwen2.5-coder:32b': ModelDef(
          id: 'qwen2.5-coder:32b',
          name: 'Qwen2.5 Coder 32B',
          apiId: 'qwen2.5-coder:32b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local', 'tools'},
          contextWindow: 32768,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'Aider-verified 73.7% (GPT-4o class). Safe fallback.',
        ),
        'qwen3:8b': ModelDef(
          id: 'qwen3:8b',
          name: 'Qwen3 8B',
          apiId: 'qwen3:8b',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'local', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Low-end floor for tool use. ~5 GB at Q4_K_M. Fits a 16 GB laptop.',
        ),
        'mistral:7b': ModelDef(
          id: 'mistral:7b',
          name: 'Mistral 7B',
          apiId: 'mistral:7b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'local', 'tools'},
          contextWindow: 32768,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'General-purpose, not code-specialized. Tool use works but weaker than Qwen3-Coder.',
        ),
        'gemma3:12b': ModelDef(
          id: 'gemma3:12b',
          name: 'Gemma 3 12B',
          apiId: 'gemma3:12b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'local'},
          contextWindow: 131072,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'No tools capability; superseded by Gemma 4. Use gemma4:26b instead.',
        ),
        'codellama:13b': ModelDef(
          id: 'codellama:13b',
          name: 'CodeLlama 13B',
          apiId: 'codellama:13b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local'},
          contextWindow: 16384,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'FIM-lineage code model. Narrates instead of calling tools. Not for agent use.',
        ),
        'codegemma:7b': ModelDef(
          id: 'codegemma:7b',
          name: 'CodeGemma 7B',
          apiId: 'codegemma:7b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local'},
          contextWindow: 8192,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'FIM-trained (80% FIM rate). Not designed for agent tool use.',
        ),
        'starcoder2:15b': ModelDef(
          id: 'starcoder2:15b',
          name: 'StarCoder2 15B',
          apiId: 'starcoder2:15b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local'},
          contextWindow: 16384,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes: 'FIM-lineage (BigCode). Code completion, not agent tool use.',
        ),
        'deepseek-coder:33b': ModelDef(
          id: 'deepseek-coder:33b',
          name: 'DeepSeek Coder 33B',
          apiId: 'deepseek-coder:33b',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'local'},
          contextWindow: 16384,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Legacy DeepSeek code model (no tools). Use qwen3-coder or devstral-small-2 instead.',
        ),
      },
    ),
    'copilot': ProviderDef(
      id: 'copilot',
      name: 'GitHub Copilot',
      adapter: 'copilot',
      compatibility: null,
      enabled: true,
      baseUrl: 'https://api.githubcopilot.com',
      docsUrl: 'https://docs.github.com/copilot',
      auth: AuthSpec(
        kind: AuthKind.oauth,
        envVar: null,
        helpUrl: 'https://github.com/login/device',
      ),
      requestHeaders: {},
      models: {
        'claude-sonnet-4-6': ModelDef(
          id: 'claude-sonnet-4-6',
          name: 'Claude Sonnet 4.6 (via Copilot)',
          apiId: 'claude-sonnet-4-6',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: 64000,
          speed: 'standard',
          cost: 'subscription',
          notes: 'Uses your GitHub Copilot subscription.',
        ),
        'gpt-4.1': ModelDef(
          id: 'gpt-4.1',
          name: 'GPT-4.1 (via Copilot)',
          apiId: 'gpt-4.1',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools'},
          contextWindow: 128000,
          maxOutputTokens: null,
          speed: 'standard',
          cost: 'subscription',
          notes: 'Uses your GitHub Copilot subscription.',
        ),
      },
    ),
    'openrouter': ProviderDef(
      id: 'openrouter',
      name: 'OpenRouter',
      adapter: 'openai',
      compatibility: 'openrouter',
      enabled: false,
      baseUrl: 'https://openrouter.ai/api/v1',
      docsUrl: 'https://openrouter.ai/docs/',
      auth: AuthSpec(
        kind: AuthKind.apiKey,
        envVar: 'OPENROUTER_API_KEY',
        helpUrl: null,
      ),
      requestHeaders: {
        'HTTP-Referer': 'https://getglue.dev',
        'X-Title': 'Glue',
      },
      models: {
        'claude-sonnet-4-6': ModelDef(
          id: 'claude-sonnet-4-6',
          name: 'Claude Sonnet 4.6 via OpenRouter',
          apiId: 'anthropic/claude-sonnet-4-6',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {
            'chat',
            'coding',
            'files',
            'json',
            'reasoning',
            'tools',
            'vision',
          },
          contextWindow: 1000000,
          maxOutputTokens: 64000,
          speed: 'standard',
          cost: 'provider_routed',
          notes: 'Useful when users want one router key.',
        ),
        'gpt-5.4-mini': ModelDef(
          id: 'gpt-5.4-mini',
          name: 'GPT-5.4 Mini via OpenRouter',
          apiId: 'openai/gpt-5.4-mini',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'coding', 'json', 'tools', 'vision'},
          contextWindow: 400000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'provider_routed',
          notes: 'Small-model fallback through a router.',
        ),
        'gemini-flash-latest': ModelDef(
          id: 'gemini-flash-latest',
          name: 'Gemini Flash Latest via OpenRouter',
          apiId: 'google/gemini-flash-latest',
          recommended: true,
          isDefault: false,
          enabled: true,
          capabilities: {'browser', 'chat', 'files', 'json', 'tools', 'vision'},
          contextWindow: 1000000,
          maxOutputTokens: null,
          speed: 'fast',
          cost: 'provider_routed',
          notes: 'Good for research and extraction workflows.',
        ),
      },
    ),
    'local-vllm': ProviderDef(
      id: 'local-vllm',
      name: 'Local vLLM',
      adapter: 'openai',
      compatibility: 'vllm',
      enabled: false,
      baseUrl: 'http://localhost:8000/v1',
      docsUrl: null,
      auth: AuthSpec(kind: AuthKind.none, envVar: null, helpUrl: null),
      requestHeaders: {},
      models: {
        'local-model': ModelDef(
          id: 'local-model',
          name: 'Local Model',
          apiId: 'local-model',
          recommended: false,
          isDefault: false,
          enabled: true,
          capabilities: {'chat', 'json', 'local'},
          contextWindow: null,
          maxOutputTokens: null,
          speed: 'depends_on_hardware',
          cost: 'local',
          notes:
              'Rename this entry to the model served by vLLM, LM Studio, or another local gateway.',
        ),
      },
    ),
  },
);
